language: java
jdk:
  - oraclejdk8
cache:
    directories:
        - $HOME/.m2
install: eval mvn clean install -DskipTests=true -B -V
script: eval mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer